---
- name: Install httpd Package 
  hosts: webservers
  become: yes 
  tasks: 

    - name: Install httpd 
      yum: 
        name: httpd
        state: latest

    - name: start/enable httpd
      service:
        name: httpd
        state: started
        enabled: yes